### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by xBuddhaSupreme** [alvinsga/candy-machine-v2#1]
How exactly would I go about changing the background? Much luv on the work homie.

**Comment by alvinsga** [comment]
Thanks! You can do that in the app.css file in the selector below, where it says background-color

```
:root {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
    Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
  background-color: black;
}
```

**Comment by xBuddhaSupreme** [comment]
And how do I make it like a png I have? Also, do you have any NFTs for sale? When I am squared up I will look to purchase forsure. Gotta support the homies that are making my project possible.

**Comment by xBuddhaSupreme** [comment]
And how would I change it to a .png I have? Do you have any NFTs for sale? When I'm squared up I'll be looking to purchase... Gotta take care of the homies making my project possible.
