### ISSUE TITLE
RangeError: Trying to access beyond buffer length

### ISSUE THREAD

**Issue by NordWayne** [alvinsga/candy-machine-v2#11]
![image](https://user-images.githubusercontent.com/36414684/148588812-a52976c6-907d-4184-a145-6827dd1bad38.png)
I use right CandyMachineId, but i got this error. How to fix it?

**Comment by psavva** [comment]
I suggest to provide exact steps how you faced this problem.
I have compiled and deployed yesterday with no issue.
