### ISSUE TITLE
When i Mint i get errors and does not work

### ISSUE THREAD

**Issue by moonvision2020** [alvinsga/candy-machine-v2#12]
Hi thank your for the repo, 

I was able to successfully deploy to vercel but when i Mint the transaction keeps failing, 

do you have any recommendations to fix this issue?

**Comment by alvinsga** [comment]
Could you post the errors you are receiving from the developer console?

**Comment by happybanana78** [comment]
Need to see the errors first to help you, plus I can already tell you that mint errors are related to a miss-configured .env file or your metaplex-candymachine isn't configured the right way. Just to be sure, did u rename the .env.example file to .env?

**Comment by iorebelsoul** [comment]
carlwilliams@Carls-iMac cli % ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts mint_one_token -e devnet -k /Users/carlwilliams/.config/solana/devnet-testwallet.json -c example
wallet public key: B8UJs45RsRxCpaB8Aoskc6FD3BRUgRcMwutVyyDFdB9s
Rejected via websocket { InstructionError: [ 4, { BorshIoError: 'Unknown' } ] }
Timeout Error caught {
  err: { InstructionError: [ 4, [Object] ] },
  slot: 108075264,
  confirmations: 0
}
(node:27426) UnhandledPromiseRejectionWarning: Error: Transaction failed: IO Error: Unexpected length of input
    at sendSignedTransaction (/Users/carlwilliams/metaplex/js/packages/cli/src/helpers/transactions.ts:136:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendTransactionWithRetryWithKeypair (/Users/carlwilliams/metaplex/js/packages/cli/src/helpers/transactions.ts:59:26)
    at async mintV2 (/Users/carlwilliams/metaplex/js/packages/cli/src/commands/mint.ts:344:5)
    at async Command.<anonymous> (/Users/carlwilliams/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:717:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
