### ISSUE TITLE
multiple pages? 

### ISSUE THREAD

**Issue by reedislost** [alvinsga/candy-machine-v2#14]
love this repo.. trying to make it work for myself but newer to dev work so bear with me if this is a dumb question.. not so much an issue. 

how do I go about creating tabs like pictured here? I'd like to be able to add a few myself but am not quite sure how to do so. Are they separate components that render? 

![image](https://user-images.githubusercontent.com/93827760/148799362-92ba6707-8810-414b-a743-e67c80cfe413.png)

**Comment by alvinsga** [comment]
You could create separate components that conditionally render or use [SvelteKit](https://kit.svelte.dev/) which comes with built in routing.

**Comment by alvinsga** [comment]
@lostdotgolf I have created a separate branch called 'svelte-kit' with the code required for navigation. Hope this helps!

**Comment by reedislost** [comment]
@alvinsga i appreciate the help, does this branch include all the original code too? or do I have to combine original repo with this? i don't see app.svelte in this branch so i assume its the latter. apologize for the nooby questions

**Comment by reedislost** [comment]
NVM i figured that out.. i see the routes are the pages. when i fire up yarn dev after running install i receive this error. looking into it
![image](https://user-images.githubusercontent.com/93827760/150681557-bec2d3f4-8185-4d6a-81da-a1c59fb23780.png)

**Comment by reedislost** [comment]
i fixed it... forgot to update the new .env file.. thanks for all the help
