### ISSUE TITLE
Hosting over HTTPS

### ISSUE THREAD

**Issue by Wanackon** [alvinsga/candy-machine-v2#15]
When hosting over https via custom domain, webpage constantly refreshing, any idea how to fix that?

**Comment by happybanana78** [comment]
I had the same issue, after hours of searching I find out that it's a vine specific issue. The only way i managed to fix it was by adding this code:

  server: {
    hmr: {
      host: `some-ngrok-subdomain.loca.lt`,
      port: 443,
    },
  },

to the vite.config.sj file.  
Then by adding this dependencies to the package.json file (remember to run the "yarn install" command again):

"devDependencies": {
  "localtunnel": "2.0.1",
  "ngrok": "^4.2.2"
}

And finally just open a screen (screen -S <whatever name you like> ) and run:

./node_modules/.bin/lt --subdomain=some-ngrok-subdomain --port=3000

I have no idea why and how this works, but it stoped the constant refreshing for me.
Btw Im running the https protocol with apache2 and i've done the ssl certificate generation and installation with the help of certbot.

Source: https://github.com/vitejs/vite/issues/4259

**Comment by Wanackon** [comment]
Good, thx. I actually manage to fixed this issue by migrate from VPS server to Heroku.

**Comment by OluAgunloye** [comment]
This is still a problem as of Vite 3.1.0!
