### ISSUE TITLE
Minting sometime doesn't recognise Phantom is installed

### ISSUE THREAD

**Issue by psavva** [alvinsga/candy-machine-v2#19]
We currently have our mint Live.
https://oikattoi-art.web.app/

You will notice that sometimes, the page will not load correctly.  It basically doesn't recognize that Phantom is installed, and says to "Get Phantom Wallet".

If you do a CTRL F5, it works!  
Please check this, and help us fix it.  
It's causing minting problems for many.

![image](https://user-images.githubusercontent.com/1454758/149791904-0b0d3e4d-0a19-4f15-95a9-db0cfe50006a.png)

**Comment by lucastoian** [comment]
I'm having the same issue, did you solved?

**Comment by seyedAhosseini** [comment]
same issue here, how to fix it ? 
error msg on chrome: Cannot read properties of undefined (reading 'connect')
on firefox: TypeError: n is undefined

**Comment by alvinsga** [comment]
Try pulling the latest changes, commit 617016aae2feab34719477f5d3934a90b72d428c should have fixed this.

**Comment by seyedAhosseini** [comment]
seems to work now, thank you
