### ISSUE TITLE
Newbie question-Integrating a theme

### ISSUE THREAD

**Issue by charles811** [alvinsga/candy-machine-v2#2]
Thanks a lot for this awesome repository. I  am almost done with my website and NFT project.

How can I integrate a frontend to this.
I tried buying a HTML theme and integrating but it is throwing errors when deploying to Vercel.

Thanks a lot for this release.
This is great.

**Comment by alvinsga** [comment]
This project is a frontend. You could use another HTML theme but you would need to map across the javascript functions to that HTML template. Alternatively, you could use TailwindCSS to customise the existing styles in this project.
