### ISSUE TITLE
Minting error

### ISSUE THREAD

**Issue by lucastoian** [alvinsga/candy-machine-v2#20]
[https://vercel-homie-app-lehdbkdwg-lucastoian.vercel.app/](url)

when I click on the Mint button ..nothing happens

what causes this problem?

**Comment by lucastoian** [comment]
![Screenshot (89)](https://user-images.githubusercontent.com/72082971/149819666-51429f63-bdd7-4f86-a33e-c05269a6b561.png)
the transaction price is not even updated

**Comment by lucastoian** [comment]
the candy machine has been successfully loaded and verified with verify_upload

**Comment by happybanana78** [comment]
I don't think it's a front-end issue, have you tried using the mint token command directly from the command line? If you did, did it work?

**Comment by LuissAlvarezz** [comment]
can you use this minting site without a custom rpc?

**Comment by kabaluyot** [comment]
This is the error I encountered too when trying using official candy-machine-ui from metaplex

**Comment by lucastoian** [comment]
I solved.. the problem was in the config.json file of metaplex

now it work:`https://www.radiolazyclub.com/`

**Comment by kabaluyot** [comment]
Hello? What specifically? Can you share your config? (without the important addresses of course)

**Comment by kabaluyot** [comment]
So for anyone experiencing this, it is the `whitelist` in config.json .. Your wallet address should have the whitelist token if it is enabled or simply set it to null to allow any wallet address to mint
