### ISSUE TITLE
Candy machine upload from images with Datahub an RPC Service

### ISSUE THREAD

**Issue by FlorianWeise** [alvinsga/candy-machine-v2#23]
Hi everbody,
I am trying to upload my images and metadata with an apikey form Datahub, command: 
npx ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload -curl https://solana--devnet--rpc.datahub.figment.io/apikey/ MY APIKEY /health -e devnet -k ~/.config/solana/devnet.json -cp config.json -c boom ./assets

something is wrong with this command, output is :
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'https://solana--devnet--rpc.datahub.figment.io/apikey/ MY APIKEY /health'

can somebody please help out, its all for devnet, I d like to understand the mechanics before deploying on mainnet. Thanks in advance.

**Comment by alvinsga** [comment]
Looks like this is more a question for the Metaplex discord or Github page
