### ISSUE TITLE
Node.js to v17.0.1 and issues with yarn start/ build candy-machine-ui/packages.json

### ISSUE THREAD

**Issue by FlorianWeise** [alvinsga/candy-machine-v2#24]
I updated the script due to problems with the node.js. I found in the internet the following sollution given: 
"scripts": {
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "deploy:gh": "gh-pages -d ./build/ --repo https://github.com/pit-v/metaplex -t true --branch gh-pages-3",
    "deploy": "cross-env ASSET_PREFIX=/metaplex/ yarn build && yarn deploy:gh"
  },

Is that a good sollution? I have personally no idea. I am no developer... Greetings.

**Comment by happybanana78** [comment]
If it works for you it's a good solution, plus if you had problems with the node 17.0.1 version, try instaling the 16.4.1, so far it's the one that gives less problems.
