### ISSUE TITLE
Adding more wallets other than Phantom

### ISSUE THREAD

**Issue by JustinMKY** [alvinsga/candy-machine-v2#25]
How would I add more Solana wallets?

**Comment by happybanana78** [comment]
You mean you wanna link more candy machines to the same front-end page?

**Comment by JustinMKY** [comment]
> You mean you wanna link more candy machines to the same front-end page?

No, I want to add more wallets connections like Sollet, Slope, etc instead of just Phantom.

**Comment by happybanana78** [comment]
Oh, in this case you actually have to ask for this feature to be implemented, or you can just write the code by your self, I have no time to look into it right now, but i can try to put something together once im home.

**Comment by alvinsga** [comment]
Unfortunately, I wont be implementing this anytime soon but I did find this project https://github.com/monomadic/solana-svelte-wallets-example which could help if you are implementing yourself.
