### ISSUE TITLE
"blinking/flickering" page

### ISSUE THREAD

**Issue by lucastoian** [alvinsga/candy-machine-v2#26]
Hy,
I edited your index.html and created my site using uikit.
I wrote my code around your  minting button component`<div id="app"></div>
              <script type="module" src="/src/main.ts"></script>
              <script>
                var global = global || window;
              </script>`

when I test my application the page is blinking, as if it were loading several times, what is the cause of this behavior? It is like a "Flickering"

**Comment by lucastoian** [comment]
https://user-images.githubusercontent.com/72082971/150629081-799c3ca5-e3d1-4607-b027-359cf2530e21.mp4

what is the cause of this behaviour?

**Comment by alvinsga** [comment]
Could be the UI code that you have added as it works fine without any changes

**Comment by happybanana78** [comment]
Could you post the code you added?

**Comment by lucastoian** [comment]
this was a css issue in my code
