### ISSUE TITLE
Mint doesn't work

### ISSUE THREAD

**Issue by ManFromNowhere1** [alvinsga/candy-machine-v2#27]
Tried with devnet and mainnet
I have checked many times and I put everything in the env file correct and it says "transaction may fail" and then just doesn't mint
It shows the price and how many are left correctly just mint is broken, I have whitelist disabled in config and time is correct

**Comment by happybanana78** [comment]
Did you set the whitelist parameter in the config to null? Plus, have you tried minting one token directly from your command line?

**Comment by ManFromNowhere1** [comment]
> Did you set the whitelist parameter in the config to null? Plus, have you tried minting one token directly from your command line?

In the metaplex config whitelist paramater yes it's set to null
yes it works through command line

**Comment by happybanana78** [comment]
How many solana do you have on your Devnet wallet?

**Comment by ManFromNowhere1** [comment]
Mint is 0.33 I have 6 sol in my Devnet wallet

**Comment by alvinsga** [comment]
I noticed this also sometimes happens if your phantom wallet is pointing to Mainet but the RPC you are using is pointing to Devnet.
