### ISSUE TITLE
Mint Live  @ Invalid Date

### ISSUE THREAD

**Issue by lucastoian** [alvinsga/candy-machine-v2#28]
![Screenshot (95)](https://user-images.githubusercontent.com/72082971/150702175-10bbd53a-2e46-40ec-9a3d-7861f928490a.png)
I put the goLiveDate in the past and I'm reciving this error...
Why? It's on mainnet

**Comment by happybanana78** [comment]
Have you tried using any other date?

**Comment by lucastoian** [comment]
the rpc provider blocked me for excess traffic , I bought a quicknode rpc and it now works
