### ISSUE TITLE
Mint Multiple

### ISSUE THREAD

**Issue by akeslo** [alvinsga/candy-machine-v2#6]
Awesome work, thank you!!

Is it possible to enable minting multiple at a time?

**Comment by alvinsga** [comment]
I don't think this is possible due to limitations on the Candy Machine v2 program.

**Comment by akeslo** [comment]
Is that true?

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts mint_multiple_tokens \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -c example \
    --number 2

![image](https://user-images.githubusercontent.com/3003773/148701881-6d0eb75f-c9a4-476f-a077-fa45c7baf0c1.png)
