### ISSUE TITLE
invalid date

### ISSUE THREAD

**Issue by gremsee** [alvinsga/candy-machine-v2#8]
Working fine on devnet, same configuration on mainnet says invalid date. 
checked the metaplex standard for the candy machine

**Comment by alvinsga** [comment]
What configuration did you use for the candy machine? If you remove sensitive information and post your config that may help us pinpoint the issue.

**Comment by gremsee** [comment]
{
    "price": 0.5,
    "number": 2222,
    "gatekeeper": null,
    "solTreasuryAccount": "Pubkey",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "14 Jan 2022 18:00:00 GMT",
    "endSettings": {
        "endSettingType": { "date":true },
        "value":"16 Jan 2022 18:00:00 GMT"
    },
    "whitelistMintSettings": {
        "mode": { "burnEveryTime": true },
        "mint": "PubkeySPL",
        "presale": true,
        "discountPrice": 0.5
        },
    "hiddenSettings": null,
    "storage": "arweave",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}

thanks!

**Comment by gremsee** [comment]
Fixed it. Has been a problem with the RPC. 
Propably the message is shown when there is no connection to the candy machine. 
Thanks for fast reply
