### ISSUE TITLE
stuck spinning after running yarn dev 

### ISSUE THREAD

**Issue by reedislost** [alvinsga/candy-machine-v2#9]
love the project and succesfully launched it one time, decided i want to try adding my own gif file to the /public folder.. shut down yarn dev server, added new gif, changed code in app.svelte to reflect path and file name to new gif, saved, ran yarn dev and now the app won't load and its stuck spinning. let me know if theres any ideas to fix. interested in using in my front end project
![image](https://user-images.githubusercontent.com/93827760/148453451-ee806235-3434-404c-bb61-ac9d4798343a.png)

**Comment by gokhancerk** [comment]
Try lock wallet or comment out this section in App.sevelte for workaround.

`      $userState.isWhiteListed = await existsOwnerSPLToken(   
        $userState.walletPublicKey,
         connection,
         $candyMachineState.state.whitelistMintSettings.mint
        )
`

**Comment by reedislost** [comment]
this worked thanks
